# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYXysRQvSN01ri3TWBEHK3cC55XXj6Tt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/WA_Fn-UseC_-HR-Employee-Attrition.csv')

print(df.shape)

print(df.dtypes)

print(df.isnull().sum())

print(df['Attrition'].value_counts())

"""Drop  constant columns"""

df.drop(columns=['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'], inplace=True)

"""Convert Attrition to binary for correlation analysis"""

df['Attrition_Binary'] = (df['Attrition'] == 'Yes').astype(int)

"""Convert OverTime to binary"""

df['OverTime_Binary'] = (df['OverTime'] == 'Yes').astype(int)

print("Cleaned shape:", df.shape)
print("Attrition rate:", round(df['Attrition_Binary'].mean() * 100, 2), "%")

"""Plot 1 — Attrition Distribution

"""

plt.figure(figsize=(6,4))
df['Attrition'].value_counts().plot(kind='bar', color=['#2ecc71','#e74c3c'], edgecolor='black')
plt.title('Overall Attrition Distribution')
plt.xlabel('Attrition')
plt.ylabel('Employee Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('plot1_attrition_distribution.png', dpi=150)
plt.show()

"""Plot-2  Attrition by Department"""

dept_attrition = df.groupby('Department')['Attrition_Binary'].mean().reset_index()
dept_attrition['Attrition_%'] = round(dept_attrition['Attrition_Binary'] * 100, 2)

plt.figure(figsize=(7,4))
sns.barplot(data=dept_attrition, x='Department', y='Attrition_%', palette='Reds_d')
plt.title('Attrition Rate by Department')
plt.ylabel('Attrition Rate (%)')
plt.tight_layout()
plt.savefig('plot2_dept_attrition.png', dpi=150)
plt.show()

"""Plot 3 — Overtime vs Attrition"""

ot_attrition = df.groupby('OverTime')['Attrition_Binary'].mean().reset_index()
ot_attrition['Attrition_%'] = round(ot_attrition['Attrition_Binary'] * 100, 2)

plt.figure(figsize=(6,4))
sns.barplot(data=ot_attrition, x='OverTime', y='Attrition_%', palette=['#2ecc71','#e74c3c'])
plt.title('Attrition Rate by Overtime Status')
plt.ylabel('Attrition Rate (%)')
plt.tight_layout()
plt.savefig('plot3_overtime_attrition.png', dpi=150)
plt.show()

"""Plot 4 — Age Distribution: Stayed vs Left"""

plt.figure(figsize=(8,4))
df[df['Attrition']=='Yes']['Age'].hist(alpha=0.7, bins=20, color='#e74c3c', label='Left')
df[df['Attrition']=='No']['Age'].hist(alpha=0.7, bins=20, color='#2ecc71', label='Stayed')
plt.title('Age Distribution: Stayed vs Left')
plt.xlabel('Age')
plt.ylabel('Count')
plt.legend()
plt.tight_layout()
plt.savefig('plot4_age_distribution.png', dpi=150)
plt.show()

"""Plot 5 — Monthly Income: Stayed vs Left"""

plt.figure(figsize=(8,4))
sns.boxplot(data=df, x='Attrition', y='MonthlyIncome', palette=['#2ecc71','#e74c3c'])
plt.title('Monthly Income: Stayed vs Left')
plt.tight_layout()
plt.savefig('plot5_income_attrition.png', dpi=150)
plt.show()

"""Plot 6 — Correlation Heatmap"""

plt.figure(figsize=(12,8))
numeric_cols = df.select_dtypes(include='number')
corr = numeric_cols.corr()['Attrition_Binary'].drop('Attrition_Binary').sort_values()

corr.plot(kind='barh', color=['#e74c3c' if x > 0 else '#2ecc71' for x in corr], figsize=(8,8))
plt.title('Feature Correlation with Attrition')
plt.xlabel('Correlation Coefficient')
plt.tight_layout()
plt.savefig('plot6_correlation.png', dpi=150)
plt.show()